# Builds the single-file, double-clickable installer: ClaudeDeck-Setup.cmd
#
# It takes install.ps1 (the canonical installer) as the single source of truth
# for the hook-merge / shortcuts / start-tray logic, swaps its "copy scripts
# from disk" step for a block that decodes the scripts embedded (base64) right
# inside the file, then wraps the whole thing in a batch+PowerShell polyglot so
# Windows runs it on a plain double-click.
#
#   powershell -ExecutionPolicy Bypass -File .\tools\build-setup.ps1
$ErrorActionPreference = 'Stop'

$root      = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$installPs = Join-Path $root 'install.ps1'
$scriptDir = Join-Path $root 'scripts'
$outCmd    = Join-Path $root 'ClaudeDeck-Setup.cmd'
$marker    = '#@CDINSTALLER@#'

# --- Version: derive scripts/version.txt from the latest git tag ------------
# The git tag is the single source of truth (e.g. tag 'v1.1.0' -> version 1.1.0).
# Falls back to the existing version.txt when the repo has no tags yet.
$versionFile = Join-Path $scriptDir 'version.txt'
$tag = (& git -C $root describe --tags --abbrev=0 2>$null)
if ($LASTEXITCODE -eq 0 -and $tag) {
  $version = ($tag -replace '^[vV]', '').Trim()
  [System.IO.File]::WriteAllText($versionFile, "$version`r`n", (New-Object System.Text.UTF8Encoding($false)))
  Write-Host ("Version (from git tag '{0}'): {1}" -f $tag, $version)
} else {
  $version = if (Test-Path $versionFile) { ([System.IO.File]::ReadAllText($versionFile)).Trim() } else { '0.0.0' }
  Write-Host ("No git tag found - keeping version.txt as-is: {0}" -f $version) -ForegroundColor Yellow
}

# --- Embed every file under scripts/ as base64 ------------------------------
$entries = Get-ChildItem $scriptDir -File | Sort-Object Name | ForEach-Object {
  $b64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($_.FullName))
  "  '$($_.Name)' = '$b64'"
}
Write-Host ("Embedding {0} script(s): {1}" -f $entries.Count, ((Get-ChildItem $scriptDir -File).Name -join ', '))

$embedBlock = @"
# --- 1) Write embedded scripts (generated by tools/build-setup.ps1) --------
New-Item -ItemType Directory -Force -Path `$dest | Out-Null
`$Embedded = @{
$($entries -join "`r`n")
}
foreach (`$name in `$Embedded.Keys) {
  [System.IO.File]::WriteAllBytes((Join-Path `$dest `$name), [Convert]::FromBase64String(`$Embedded[`$name]))
}
Write-Host "  Scripts -> `$dest"

"@

# --- Take install.ps1, swap its "copy scripts" step for the embed block -----
$installer = [System.IO.File]::ReadAllText($installPs)
$pattern   = '(?s)# --- 1\) Copy scripts.*?(?=# --- 2\) Merge hooks)'
if ($installer -notmatch $pattern) { throw "Could not find the 'copy scripts' section in install.ps1 - did its section markers change?" }
$installer = [regex]::Replace($installer, $pattern, { $embedBlock })

if ($installer.Contains($marker)) { throw "The installer text contains the payload marker '$marker' - pick a different marker." }

# --- Batch header: extract everything after the marker, run it as PowerShell -
# Kept strictly ASCII and BOM-free so cmd.exe parses the header cleanly.
$batch = @"
@echo off
setlocal EnableExtensions
title ClaudeDeck Setup
set "CDSELF=%~f0"
set "CDPS=%TEMP%\ClaudeDeck-Setup.ps1"
powershell -NoProfile -ExecutionPolicy Bypass -Command "`$c=[IO.File]::ReadAllText(`$env:CDSELF);`$i=`$c.LastIndexOf('$marker');`$t=`$c.Substring(`$i+$($marker.Length));[IO.File]::WriteAllText(`$env:CDPS,`$t,[Text.UTF8Encoding]::new(`$false))"
if errorlevel 1 goto fail
powershell -NoProfile -ExecutionPolicy Bypass -File "%CDPS%"
if errorlevel 1 goto fail
del "%CDPS%" >nul 2>&1
echo.
echo Press any key to close this window.
pause >nul
endlocal
exit /b 0
:fail
del "%CDPS%" >nul 2>&1
echo.
echo ClaudeDeck setup failed. Press any key to close.
pause >nul
endlocal
exit /b 1

$marker
"@

# Join with CRLF (batch wants CRLF) and write WITHOUT a BOM (a BOM breaks .cmd).
$content = ($batch -replace "`r?`n", "`r`n") + ($installer -replace "`r?`n", "`r`n")
[System.IO.File]::WriteAllText($outCmd, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host ("Wrote {0} ({1:N0} bytes)" -f $outCmd, (Get-Item $outCmd).Length) -ForegroundColor Green
